# -*- coding: utf-8 -*-
"""Homework_Basic_Programming_Nur_Aula.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vTxSoX_j3Zo36ZcDh3K45xOJ8NU9XulJ
"""

#Tulis fungsi Python untuk menemukan angka terbesar dari tiga angka.
def find_largest_number(number1, number2, number3): #Input number1, number2, number3
  """Python function to find the largest number among three numbers."""
  if number1 >= number2 and number1 >= number3: #If number1 is greater than or equal to number2 and number1 is greater than or equal to number3, then
    return number1 #Return number1
  elif number2 >= number1 and number2 >= number3: #If number2 is greater than or equal to number1 and number2 is greater than or equal to number3, then
    return number2 #Return number2
  else: #Otherwise (when neither of the above conditions is met), then
    return number3 #Return number3

#Example
find_largest_number(56465, 54987, 56897)

#Tulis fungsi Python untuk menjumlahkan semua angka dalam list.
def sum_numbers_in_list(*args): #Define a function called 'sum_numbers_in_list' that takes a variable number of arguments using *args, allowing one to pass any number of lists or individual numeric values as input.
  """Python function to sum all the numbers in a list."""
  total = 0 #Initialize a variable "total" to 0 to keep track of the sum.
  for number in args: #Use a loop to iterate through each number in the input list.
      total += number #For each number in the list, add it to the "total."
  return total #Once all numbers in the list have been added to the "total," return the "total" as the result.

#Example
sum_result = sum_numbers_in_list(564654, 8762198, 9846198, 15465, 597498265)
print("The sum of all numbers in the list is:", sum_result)

#Tulis fungsi Python untuk mengalikan semua angka dalam list.
def multiply_numbers_in_list(*args): #Define a function called 'multiply_numbers_in_list' that takes a variable number of arguments using *args, allowing one to pass any number of lists or individual numeric values as input.
  """Python function to multiply all the numbers in a list."""
  result = 1 #Initialize a variable "result" to 1 to store the product.
  for number in args: #Use a loop to iterate through each number in the input list.
      result *= number #For each number in the list, multiply it to the "result."
  return result #Once all numbers in the list have been multiplied into the "result.", reutrn the "result" as the final product.

#Example
product_result = multiply_numbers_in_list(8, 2, 3, -1, 7)
print("The product of all numbers in the list is:", product_result)

#Tulis program Python untuk membalikkan string.
def reverse_string(string): #Define a function called "reverse_string" that takes a string as input.
  """Python program to reverse a string."""
  return string[::-1] #Use slicing with [::-1] to reverse the input string.

#Example
string = "Hi, everyone!"
reversed_sentence = reverse_string(string)
print("Reversed sentence:", reversed_sentence)

#Tulis fungsi Python yang menerima string dan menghitung jumlah huruf besar dan huruf kecil.
def count_letters(string): #Define a function called "count_letters" that takes a string as input.
  """Python function that takes a string and counts the number of uppercase and lowercase letters."""
  uppercase_count = 0 #Initialize variable "uppercase_count" to 0 to keep track of the counts of uppercase letters.
  lowercase_count = 0 #Initialize variable "lowercase_count" to 0 to keep track of the counts of lowercase letters.

  for character in string: #Use a loop to Return both "uppercase_count" and "lowercase_count" as the result.iterate through each character in the input string.
    if character.isupper(): #For each character, check if it's an uppercase letter using the "isupper()" method.
       uppercase_count += 1 #If it is, increment the "uppercase_count" by 1.
    elif character.islower(): #Check if it's a lowercase letter using the "islower()" method.
       lowercase_count += 1 #If it is, increment the "lowercase_count" by 1.

  return uppercase_count, lowercase_count #Return both "uppercase_count" and "lowercase_count" as the result.

#Example
string = "This is for Homework Basic Programming"
uppercase, lowercase = count_letters(string)
print("Number of uppercase letters:", uppercase)
print("Number of lowercase letters:", lowercase)

#Tulis fungsi Python yang mengambil daftar dan mengembalikan list baru dengan elemen unik dari list pertama.
def unique_elements(input_list): #Define a function called "unique_elements" that takes a list as input.
  """Python function that takes a list and returns a new list with unique elements from the first list."""
  unique_list = list(set(input_list)) #Convert the input list to a list with unique elements by first converting it to a set and then back to a list.
  return unique_list #Return the list with unique elements as the result.

#Example
sample_list = [1,2,3,3,3,3,4,5]
result_list = unique_elements(sample_list)
print("List with unique elements:", result_list)

#Tulis fungsi Python yang menggunakan angka sebagai input parameter dan periksa angkanya prima atau tidak.
def is_prime(number): #Define a function called "is_prime" that takes a number as input.
  """Python function that takes a number as an input parameter and checks whether it is prime or not."""
  if number <= 1:
      return False  # Numbers less than or equal to 1 are not prime.
  elif number <= 3:
      return True  # 2 and 3 are prime numbers.
  elif number % 2 == 0 or number % 3 == 0:
      return False  # Numbers divisible by 2 or 3 are not prime.
  i = 5
  while i * i <= number:
      if number % i == 0 or number % (i + 2) == 0:
          return False  # Numbers divisible by factors other than 1, itself, 2, and 3 are not prime
      i += 6
  return True  # If all tests fail, the number is prime

#Example
number = 17
if is_prime(number):
    print(number, "is a prime number.")
else:
    print(number, "is not a prime number.")

#Tulis program Python untuk mencetak bilangan genap dari list yang diberikan.
def print_even_numbers(numbers): #Define a function called "print_even_numbers" that takes a list of numbers as input.
  """Python program to print even numbers from a given list."""
  for number in numbers: #For each number in the input list:
      if number % 2 == 0: #Check if the number is even by using the modulo operator: if number % 2 equals 0.
          print(number) #If the number is even, print the number.

#Example
number_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print("Even numbers in the list:")
print_even_numbers(number_list)

