# -*- coding: utf-8 -*-
"""Basic Programming Conditions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18yDh-vYPO6MEGnAkb2FhRZT0gN625Y92
"""

!python -V

lang = input("What's the programming language you want to learn? ")

match lang:
    case "JavaScript":
        print("You can become a web developer.")

    case "Python":
        print("You can become a Data Scientist")

    case "PHP":
        print("You can become a backend developer")

    case "Solidity":
        print("You can become a Blockchain developer")

    case "Java":
        print("You can become a mobile app developer")
    case _:
        print("The language doesn't matter, what matters is solving problems.")

type(5)

type('5')

"""## Boolean Data Type"""

5 == '5'

5 == 5

"""## Boolean Logic

### OR
"""

5 == 5 or 5!=1
#(TRUE) or (TRUE) = TRUE

5 == 5 or 5==1
#(TRUE)  or (FALSE) = TRUE

5 != 5 or 5==1
#(FALSE)  or (FALSE) = FALSE

"""### AND"""

5 == 5 and 5!=1
#(TRUE) and (TRUE) = TRUE

5 == 5 and 5==1
#(TRUE)  and (FALSE) = FALSE

5 != 5 and 5==1
#(FALSE)  or (FALSE) = FALSE

"""## Conditional Statement

**Format penulisan if statement**
"""

if statement:
    expression

name = 'Rizki'

if name=='Rizki':
    print('Rizki')

"""**General Structure for if else statement**"""

# Define a variable
condition = True

# Check the condition in the if statement
if condition:
    print("Expression 1")
else:
    print("Expression 2")

a = 10
a

a = 25

a

if a == 5:
    print('a is 5')
else:
    print('a is not 5')
print('hello world')

if a > 15:
    print('a is greater than 15')
else:
    print('a is less than 15')
print('hello world')

a = 10
b = 5
c = 20
total = a+b+c
total

"""**General Structure Multiple If statement**"""

# Define your statements or conditions
statement1 = True
statement2 = False
statementx = True

# Use the variables in an if-elif structure
if statement1:
    print("Expression 1")
elif statement2:
    print("Expression 2")
elif statementx:
    print("Expression x")
else:
    print("Default Expression")

if total == 10:
    print('total is equal to 10')
elif total == 20:
    print('total is equal to 20')
elif total == 30:
    print('total is equal to 30')
else:
    print('total is not 10, 20, or 30')
    print('hallo')

"""### Nested IF statement"""

num = -11

"""1. Kita mau cek apakah num itu positive or negative number
2. Positve or negative number apakah lebih besar atau lebih dari angka tertentu
"""

if num > 0:
    print('num is positive number')
    if num > 10:
        print('num is greater than 10')
    else:
        print('num is less than 10')
else:
    print('num is negative number')
    if num < -10:
        print('num is less than negative 10')
    else:
        print('num is greater than negative 10')

"""# Mini Practice Question

A company decided to give bonus of 5% to employee if his/her year of service is more than 5 years. Ask user for their salary and year of service and print the net bonus amount.
"""

salary = input()
years = input()
salary = float(salary)
years = float(years)

if years > 5:
    salary_total = salary * 1.05
    bonus = salary * 0.05
else:
    salary_total = salary
    bonus = 0

print(salary_total, bonus)

"""Take values of length and breadth of a rectangle from user and check if it is square or not"""

length = input()
width = input()
length = float(length)
witdth = float(width)

length, type(length)

witdth, type(witdth)

if length == witdth:
    print('it is a square')
else:
    print('it is not a square')

"""A shop will give discount of 10% if the cost of purchased quantity is more than 1000. Ask user for quantity Suppose, one unit will cost 100. Judge and print total cost for user"""

name = input('please enter your name: ')

qty = input()
qty = int(qty)
print('The quantity is {}'.format(qty))
unit_price = 100
disc = 0.1
total_cost = qty * unit_price

if total_cost > 1000:
    total_cost = total_cost * (1 - disc)
else:
    total_cost = total_cost

print('The total cost is {} and discount is {}'.format(total_cost, disc))

"""Write a program to print absolute value of a number entered by user. E.g.:
1. INPUT: 1        OUTPUT: 1
2. INPUT: -1        OUTPUT: 1

"""

input_num = input()
input_num = float(input_num)
print('The input is {}'.format(input_num))

if input_num < 0:
    input_num = abs(input_num)
    output_num = input_num
else:
    output_num = input_num

print(output_num)

