# -*- coding: utf-8 -*-
"""Basic Programming Iterations (2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TQdh9ayoWnPNT7VPvhoxGSKvyYeJMxfZ

# While Loop Statement

## print angka dari 1 sampai 5
"""

print(1)
print(2)
print(3)
print(4)
print(5)

i = 5
num = 0
while i < 5:
    print(num)
    num = num + 1

# Define a test expression
test_expression = True

# Use the test expression in a while loop
while test_expression:
    # Code block to be executed as long as test_expression is True
    print("Executing block of code")

    # Ensure that there's a way to update the test_expression, or the loop will run indefinitely
    # For example, you might modify the test_expression inside the loop
    test_expression = False  # This is just an example; you should modify it based on your logic

list_a = [1, 2, 4, 5]

list_a[0]

"""## Print hello world / string sebanyak 5 kali"""

i = 0

while i<5: # test expression
    #print(i)
#     print("Hello World")
#     i = i + 1

    print("Initial i value", i)
    print('hello world')
    i = i+1
    print("Updated i value", i)

"""print number from 3 to 5"""

num = 3 # initial condition

while num < 6: # test expression
    print(num) # print num
    #print("\n")
    num = num + 1 # increment num by 1
    #print('last value of num is {}'.format(num))

print('It is done')

"""# For Loop Statement"""

# Define a sequence (e.g., a list)
sequence = [1, 2, 3, 4, 5]

# Use the sequence in a for loop
for val in sequence:
    # Code block to be executed for each element in the sequence
    print(val)

"""## Print hello world / string sebanyak 5 kali"""

numbers = [10, 20, 30, 40, 100] # list
numbers # sequence opsi 1

len(numbers)

numbers_ = (10, 20, 30, 40, 100) # sequence opsi 2

for i in numbers:
    print("The list element is", i)
    print("Hello World")

"""## Menghitung jumlah huruf O dari sebuah kata**"""

kata = "GOOGLE"

a = 5

a

a == 1

i

student = ["Male", "Female", "Male"]
for i in student:
    print(i)

for i in kata:
    print(i)

result = []
for i in kata:
    if i == 'O':
        #print(i)
        result.append(i)
print(result)

print("Jumlah huruf O di sebuah kata adalah", len(result))

"""## Menghitung penjumlahan dari angka yang ada**"""

numbers = [10, 20, 30, 40, 100] # list
numbers

total = 0
for num in numbers:
    print(num)
    total = total + num

print("\nThe sum of total all numbers are {}".format(total))

# printing 3 to 5
for i in range(3, 6):
    print(i)

words = ['hello', 'world', 'hi', 'everyone'] # list

for w in words:
    print(w +'!')

# mengiterasi sebuah list, dictionary, tuple, for loop
# mengiterasi berdasarkan sebuah prasyarat / kondisi, while loop

words = ['hello', 'world', 'hi', 'everyone']
counter = 0
number = len(words)

while counter < number:
    word = words[counter]
    print(word + ' !')
    counter = counter + 1

"""# Nested Loop"""

buah = ["apple", "banana", "orange"]
rasa = ["manis", "asam"]

for b in buah:
    for r in rasa:
        print(b+" "+r)

numbers = ["1", "2", "3", "4"]
words = ['hello', 'world', 'hi', 'everyone']

for num in numbers: # outer loop
    for word in words: # inner loop
        print(num + word)

# hasil nested loop = jumlah iterasi inner loop x jumlah iterasi outer loop

"""# Break and Continue Statement"""

words = "testcase"

for w in words:
    if w == "a":
        break
    print(w)

"""## Print even numbers only"""

10%2

a = 10
b = 5

a == b

# opsi benar
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# print only even number
for num in numbers:
    #print("Num is", num)
    if num % 2 != 0:
        #print(num)
        continue
    else:
        print(num)

"""**Tanpa Continue Statement**"""

for num in numbers:
    if num % 2 == 0:
        print(num)

#opsi salah
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#print only even number
for num in numbers:
    print("Num is", num)
    if num % 2 == 0:
        break

"""**Terminate printing if "a" alphabet is appear**"""

string = 'hello hallo'

for s in string:
    if s == 'a':
        break
    print(s)

"""# Range Function"""

# Define start, stop, and step
start = 1
stop = 10
step = 2

# Use range with the defined parameters
for i in range(start, stop, step):
    print(i)

list(range(0, 5, 1))

result = list(range(0, 101, 10))
result

for i in range(0, 101, 10):
    print(i * 2)

"""# Mini Practice

Write a Python program to find those numbers which are divisible by 7 and multiple of 5, between 1500 and 2700 (both included)
"""

numbers = range(1500, 2701,1)

result = []
for i in numbers:
    if (i % 7 == 0) and (i % 5 == 0):
        result.append(i)
print(result)

"""Buatlah program Python untuk menghitung jumlah bilangan genap dan ganjil dari deretan bilangan"""

numbers = list(range(0, 50, 1))

result_even = []
result_odd = []

for i in numbers:
    if i == 0:
        continue
    if i % 2 == 0:
        result_even.append(i)
    else:
        result_odd.append(i)

print("Even numbers are {}".format(result_even))
print("Odd numbers are {}".format(result_odd))

"""Write a Python program that accepts a string and calculate the number of digits and letters. Sample Data : Python 3.2. Letters 6. Digits 2

"""

'1'.isnumeric()

strings = ['Andi', 'Budi123', 'Albert']
number = []
alphabet = []

for s in strings:
    for a in s:
        if a.isnumeric():
            number.append(a)
        elif a.isalpha():
            alphabet.append(a)



print("Number of Digits are {}".format(len(number)))
print("Number of Letters are {}".format(len(alphabet)))

number

a = []
a.append(3)
a

numbers = [1,2]
numbers.append(3)
print(numbers)

"""# Enumarate and Zip"""

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] # list
numbers
total = 0
for i, num in enumerate(numbers):
    print(i, num)

    total = total + num

print("\nThe sum of total currently is {}".format(total))

for num, word in zip(numbers, words):
    print(num, word)

"""# Exploring Use Case"""

nasabah = ['123bogor', '123jakarta', '345bogor', '456bandung', '789surabaya']

result = []
for n in nasabah:
    if 'bogor' in n:
        result.append(n)

print(len(result))

final_result = []
result = []
for n in nama:
    n = n.lower()
    for w in words:
        if w in n:
            result.append(n)
            final_result.append(result)

print(len(final_result))

n = 'Andi'
n = n.lower()
n

"""# Additionals"""

seq = {"Jakarta": "Indonesia", "Manila": "Filipina"}

for i,j in seq.items():
    print(i, j)

number_list = [ x for x in range(20) if x % 2 == 0]
print(number_list)

